DROP DATABASE IF EXISTS q5v2n05u2fefbss0;
CREATE DATABASE burger_db;
USE burger_db;

CREATE TABLE burgers(
id INT AUTO_INCREMENT NOT NULL,
name VARCHAR(255) NOT NULL,
devoured BOOLEAN NOT NULL DEFAULT FALSE,
PRIMARY KEY(id)
);